name: Deploy VPC


on:
  push:
    branches: [ "main" ]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

       - name: Initialize terraform 
        run: |
         Terraform init 

  
       - name: Configure workspace
        run: |
         Terraform workspace new dev || terraform workspace select dev 

  - name: Plan
        run: |
         terraform plan
         
         



         
     

         
            
