name: Deploy asg

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

     - uses: actions/checkout@v4

     - name: Initialize terraform
       working-directory: asg
       run: |
         Terraform init 

  
     - name: Configure workspace
       working-directory: asg
       run: |
         Terraform workspace new dev || terraform workspace select dev 

     - name: Plan
      working-directory: asg
      run: |
       terraform plan

  
     - name: Apply
       working-directory: asg
       run: |
       echo ""applying"
       #terraform apply -auto-approve       



         
     

         
            
